name: Notify Discord on PR events

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_USER="${{ github.event.pull_request.user.login }}"
          PR_HEAD="${{ github.event.pull_request.head.ref }}"
          PR_BASE="${{ github.event.pull_request.base.ref }}"
          REPO="${{ github.repository }}"

          MESSAGE="Pull Request by ${PR_USER}\n"
          MESSAGE+="Branch: ${PR_HEAD} → ${REPO}:${PR_BASE}\n"
          MESSAGE+="Title: ${PR_TITLE}\n"
          MESSAGE+="Link: ${PR_URL}"

          JSON_PAYLOAD=$(jq -n --arg content "$MESSAGE" '{content: $content}')

          curl -H "Content-Type: application/json" \
               -X POST "$DISCORD_WEBHOOK" \
               -d "$JSON_PAYLOAD"
